// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smartspendingtracker;

#nullable disable

namespace Smartspendingtracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smartspendingtracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NameArabic");

                    b.HasIndex("NameEnglish");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF6B6B",
                            IconClass = "fa-utensils",
                            Keywords = "أكل,مطعم,قهوة,فطار,غدا,عشا,طعام,food,restaurant,coffee,lunch,dinner,breakfast",
                            NameArabic = "طعام",
                            NameEnglish = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4ECDC4",
                            IconClass = "fa-car",
                            Keywords = "مواصلات,بنزين,تاكسي,سيارة,transport,taxi,gas,car,fuel,uber",
                            NameArabic = "مواصلات",
                            NameEnglish = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#95E1D3",
                            IconClass = "fa-file-invoice-dollar",
                            Keywords = "فواتير,كهرباء,ماء,نت,انترنت,bills,electricity,water,internet,utilities",
                            NameArabic = "فواتير",
                            NameEnglish = "Bills"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F38181",
                            IconClass = "fa-home",
                            Keywords = "إيجار,ايجار,سكن,rent,housing",
                            NameArabic = "إيجار",
                            NameEnglish = "Rent"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#AA96DA",
                            IconClass = "fa-shopping-bag",
                            Keywords = "تسوق,ملابس,شراء,shopping,clothes,purchase,buy",
                            NameArabic = "تسوق",
                            NameEnglish = "Shopping"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#6C757D",
                            IconClass = "fa-folder",
                            Keywords = "أخرى,متفرقات,other,miscellaneous,various",
                            NameArabic = "أخرى",
                            NameEnglish = "Other"
                        });
                });

            modelBuilder.Entity("Smartspendingtracker.Models.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromCurrency")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ToCurrency")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month", "FromCurrency", "ToCurrency")
                        .IsUnique();

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromCurrency = 2,
                            Month = 2,
                            Rate = 13.5m,
                            ToCurrency = 1,
                            UpdatedAt = new DateTime(2026, 2, 6, 22, 40, 44, 366, DateTimeKind.Utc).AddTicks(3953),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Smartspendingtracker.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConvertedAmountInEGP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ExchangeRateUsed")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DateTime");

                    b.HasIndex("DateTime", "CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Smartspendingtracker.Models.Expense", b =>
                {
                    b.HasOne("Smartspendingtracker.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Smartspendingtracker.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
